host: "localhost"
master_user: "root"
user: "faq_user"
db_password: "gAAAAABij43fmytcza2S34qdwBxP8UiwVJbu8JhriTjATZNDurRFnb1xgtQw2QfIDEKsXMHACTB3xBf8OS0fsbYlIxCDLefEPAelb_HtUCcmgKm_Ch_bIbkcG9eB6dHJ3f_6hYhbuc9VMrmI4AMfsAbD-he5Y4QyWnszf3bBhsidEqiHvfIzDvvdh9x5Fb_kGKgHJMPYIi0k-J7bVdiRbDP2bGlIPFBgqTs84qxdzMy5Tjeo46X6eRK1UWurjMi6iwqj0bACiY6-Z35YOGhhrl6TiDf61IcL5eDHgMwxZnMHkKT-ZkSKcofGO4DSor5hIYHf6daSkaIFcJ-Gr8GykqXeK5Srk02lFKyV52OCnQAjX9WCVue6lLdvvivfjLLa42KCDYVBPjPl"
user_password: "gAAAAABilGREsfbj9HmVvsoCyLAmkyeDTeS7qUy629jFXyEm9hWR_tZewaIlDuAxCIPskPd6zduWOIm7k9Ex6_TRJ59tdGOkRDvhpH-hTdZBclj7JFGxcQSYoX50sOwb8UygakbAxD9sAbyAB6G6HM0AW9HEcNy1Zwwi1EjA_MNMIcWTAOY1qIgBPOHYv0y5zlrM9JysKwV6GyYHZrfxFoNOk-EwHNAt8L0pSs8dch6-zQkdis7s0Y5Cwx0O5K7PfVmNq3-XV810vXaaVsZuM-T00LyIqtogJlYcR0Dl1TCvNZIj3myaWdZNx2UcATv-D16zqaVH-Dbtp91S4l2JY7LEj0PXb2hrQV8DdKXSZJmW2Wly6LCew1DhVv8zQNir4n0diNHXg6To"
db_name: "python_faq"
auto_commit_flag: true
cursor_type: "dict"
secret: "secret/secret.key"